### PR TITLE
Replace production public keys

### PR DESCRIPTION
**Pull request by joseph-reynolds**
This replaces the production public keys:
- The primary key is replaced.
- The backup key is moved and replaced.

Signed-off-by: Joseph Reynolds <joseph-reynolds@charter.net>

### CODE REVIEW

**Comment by joseph-reynolds** [comment]
This gets built into the image via https://github.ibm.com/openbmc/openbmc/pull/1797

**Review by cjengel — COMMENTED** [review]
Why is there a copy of the backup key in the root dir ? Was this by accident?  I don't see the normal key there

**Review by cjengel — APPROVED** [review]
Nevermind, my previous comment.  Wasn't reading the commit in github correctly

**Comment by joseph-reynolds** [comment]
The code to install the keys into the BMC readonly file system is https://github.ibm.com/openbmc/openbmc/pull/1797

**Pull request merged**
