### PR TITLE
Add P11 ACF verification public keys

### PR DESCRIPTION
**Pull request by cjengel**

### CODE REVIEW

**Review by geissonator — COMMENTED** [review]
Updates needed over in https://github.com/ibm-openbmc/ibm-acf/blob/master/subprojects/ce-login/meson.build to move us to the new P11 files?

**Comment by cjengel** [comment]
> Updates needed over in https://github.com/ibm-openbmc/ibm-acf/blob/master/subprojects/ce-login/meson.build to move us to the new P11 files?

The only thing in the meson file is reference to the lab keys .  The P10/P11 lab keys are identical but for consistency I copied the P10->P11 names.  I believe there will be changes required to the ACF pam module that processes requests to use the new key which isn't in this repo.  @joseph-reynolds agree?

**Comment by joseph-reynolds** [comment]
If the only purpose of this commit is to add the new P11 keys, it seems okay.
Additional changes are needed in a couple of spots to use these new keys (beginning in the 1110 branch?):
- The recipe https://github.com/ibm-openbmc/openbmc/blob/1050/meta-ibm/recipes-phosphor/ibm-acf/ibm-acf.bb installs the 4 public keys into the BMC's read-only file system in /srv/ibm-acf/*.
- The ibm-acf repo subprojects/ce-login/meson build file.
- I'm not sure if we need to change anything in https://github.com/ibm-openbmc/phosphor-certificate-manager/blob/1060/bmc-acf/acf_manager.cpp

**Review by joseph-reynolds — APPROVED** [review]
Seems okay to add the new keys.  Additional work is needed to actually use them on the BMC.

**Comment by cjengel** [comment]
Thanks @joseph-reynolds , and will you track that additional work ? 
@geissonator , any other comments or good to get this merged?

**Review by geissonator — APPROVED** [review]
Will let Joseph open a Jira to track the remaining work to use these.

**Review by dndfrink-ibm — CHANGES_REQUESTED** [review]
rename p11-celogin-prod to p11-celogin-prod-pub

**Comment by joseph-reynolds** [comment]
The followup recipe change which builds these keys into the firmware image is https://github.ibm.com/openbmc/openbmc/pull/5381

**Pull request merged**
