### PR TITLE
pam_ibmacf Reduce journal messages

### PR DESCRIPTION
**Pull request by joseph-reynolds**
This improves the set of pam_syslog messages sent by the pam_ibmacf module.  It reduces the number of messages sent in the normal cases and sends usable diagnostic messages.

Normally the ACF is checked against the primary production key, the backup production key, and if field mode is disabled, against the development key.  However, there is no point in continuing if the first check failed in a way that the subsequent checks would also fail.  The code was changed to give up in this case.

Tested: A variety of authentication outcomes
- ACF missing
- Success
- Bad password
- Missing keys

Signed-off-by: Joseph Reynolds <joseph-reynolds@charter.net>

### CODE REVIEW

**Comment by bentyner** [comment]
I see the reduction of journal messages and new diagnostics being returned but it seems like there is more to this change that journal cleanup (?)
particularly starting here:
// Check the ACF with the production key. There are three outcomes:
...

**Comment by joseph-reynolds** [comment]
> it seems like there is more to this change that journal cleanup

Good catch.  Yes, I've also changed the behavior: if the first validation attempt (`verifyACF(acfProdPubKeypath,...)`) fails because either the `acfProdPubKeypath` file is missing or the ACF was not signed with that key, then we can try the next key.  Otherwise there is no point to continue.
I'll update the comment above.

**Comment by joseph-reynolds** [comment]
I wrote related https://github.com/openbmc/openbmc/issues/3847 for an upstream solution for how we can toggle debug messages as needed.

**Comment by joseph-reynolds** [comment]
I force-pushed an updated commit message.  There were no code changes.

**Comment by bentyner** [comment]
Are you logging data here that may hint at ways to potentially break security ?
    pam_syslog(pamh, LOG_WARNING, "ACF service auth failed 0x%X: %s"
               " (serial=%s, sRc1=0x%X, sRc2=0x%0x, sRc3=0x%X)",
               sRc, errMsg, mSerialNumber.c_str(), sRc1, sRc2, sRc3);

**Review by bentyner — APPROVED** [review]

**Comment by joseph-reynolds** [comment]
Bumped by https://github.ibm.com/openbmc/openbmc/pull/2053

> Are you logging data here that may hint at ways to potentially break security

I hope not.  Note that only authorized users can get this log entry.  The system serial number is known to any network user.
The ACF security design is durable in that giving away why authentication failed doesn't give an attacker more information than they had.  Considering whole design and implementation is open source.  The key secret remains the service account password, and the diagnostic messages doesn't help crack that.

**Pull request merged**
